<?php
/**
 * Plugin Name:       Personio Integration Light
 * Description:       Provides recruiting handling for Personio.
 * Requires at least: 6.2
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            laOlaWeb
 * Author URI:        https://laolaweb.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       personio-integration-light
 *
 * @package personio-integration-light
 */

use PersonioIntegrationLight\Plugin\Init;

// do nothing if PHP-version is not 8.0 or newer.
if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
	return;
}

// set version number.
define( 'WP_PERSONIO_INTEGRATION_VERSION', '@@VersionNumber@@' );

// save plugin-path.
define( 'WP_PERSONIO_INTEGRATION_PLUGIN', __FILE__ );

// get autoloader generated by composer.
if ( file_exists( __DIR__ . '/lib/autoload.php' ) ) {
	require_once __DIR__ . '/lib/autoload.php';
}

// get constants.
require_once __DIR__ . '/inc/constants.php';

// on activation.
register_activation_hook( WP_PERSONIO_INTEGRATION_PLUGIN, array( Init::get_instance(), 'activation' ) );

// on deactivation.
register_deactivation_hook( WP_PERSONIO_INTEGRATION_PLUGIN, array( Init::get_instance(), 'deactivation' ) );

// Start the 'foo' timer:
add_action(
	'plugins_loaded',
	function () {
		Init::get_instance()->init();
	}
);

add_action( 'personio_integration_installer', function() {
	update_option( 'personioIntegrationUrl', 'https://dev-partner-laolaweb-gmbh.jobs.personio.de' );
	update_option( 'wp_easy_setup_completed', 1 );
	update_option( 'personioIntegration_debug', 1 );
});
