<?php
/**
 * Plugin Name:       Personio Integration Light
 * Description:       Provides recruiting handling for Personio.
 * Requires at least: 4.9.24
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            laOlaWeb
 * Author URI:        https://laolaweb.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       personio-integration-light
 *
 * @package personio-integration-light
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

use PersonioIntegrationLight\Plugin\Init;
use PersonioIntegrationLight\Plugin\Installer;
use PersonioIntegrationLight\Plugin\Update;

// do nothing if PHP-version is not 8.0 or newer.
if ( PHP_VERSION_ID < 80000 ) { // @phpstan-ignore smaller.alwaysFalse
	return;
}

// set version number.
const WP_PERSONIO_INTEGRATION_VERSION = '@@VersionNumber@@';

// save plugin-path.
const WP_PERSONIO_INTEGRATION_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// get constants.
require_once __DIR__ . '/inc/constants.php';

// add deprecated.
require_once __DIR__ . '/deprecated/deprecated.php';

// on activation.
register_activation_hook( WP_PERSONIO_INTEGRATION_PLUGIN, array( Installer::get_instance(), 'activation' ) );

// on deactivation.
register_deactivation_hook( WP_PERSONIO_INTEGRATION_PLUGIN, array( Init::get_instance(), 'deactivation' ) );

add_action(
	'plugins_loaded',
	static function () {
		Update::get_instance()->init();
		Init::get_instance()->init();
	}
);
