<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package personio-integration-light
 */

use PersonioIntegrationLight\Plugin\Uninstaller;

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if PHP-version is not 8.1 or newer.
if ( version_compare( PHP_VERSION, '8.1', '<' ) ) {
	return;
}

// set version number.
define( 'WP_PERSONIO_INTEGRATION_VERSION', '@@VersionNumber@@' );

// save plugin-path.
define( 'WP_PERSONIO_INTEGRATION_PLUGIN', __FILE__ );

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// include necessary files.
require 'inc/constants.php';

// run uninstaller.
Uninstaller::get_instance()->run( array( get_option( 'personioIntegrationDeleteOnUninstall', 0 ) ) );
