<?php

/**
 * Define each taxonomy
 */
const WP_PERSONIO_INTEGRATION_TAXONOMY_RECRUITING_CATEGORY = 'personioRecruitingCategory';
const WP_PERSONIO_INTEGRATION_TAXONOMY_OCCUPATION_CATEGORY = 'personioOccupationCategory';
const WP_PERSONIO_INTEGRATION_TAXONOMY_OFFICE = 'personioOffice';
const WP_PERSONIO_INTEGRATION_TAXONOMY_DEPARTMENT = 'personioDepartment';
const WP_PERSONIO_INTEGRATION_TAXONOMY_EMPLOYMENT_TYPE = 'personioEmploymentType';
const WP_PERSONIO_INTEGRATION_TAXONOMY_SENIORITY = 'personioSeniority';
const WP_PERSONIO_INTEGRATION_TAXONOMY_SCHEDULE = 'personioSchedule';
const WP_PERSONIO_INTEGRATION_TAXONOMY_EXPERIENCE = 'personioExperience';
const WP_PERSONIO_INTEGRATION_TAXONOMY_LANGUAGES = 'personioLanguages';
const WP_PERSONIO_INTEGRATION_TAXONOMY_KEYWORDS = 'personioKeywords';