<?php
/**
 * File for a text field in the settings, whose content is only generated when it is shown.
 *
 * @package personio-integration-light
 */

declare(strict_types=1);

namespace PersonioIntegrationLight\Plugin\Admin;

// prevent direct access.
defined( 'ABSPATH' ) || exit;

use easySettingsForWordPress\Fields\TextInfo;

/**
 * Text field in the settings, whose description is generated by a callback when it is shown.
 *
 * The settings are registered on every request, so costly content (e.g. a status, which needs database queries)
 * should only be generated on the settings page itself.
 */
class Callback_TextInfo extends TextInfo {
	/**
	 * The callback, which returns the description.
	 *
	 * @var callable|null
	 */
	private $callback = null;

	/**
	 * The generated description, as the field reads it more than once.
	 *
	 * @var string|null
	 */
	private ?string $generated = null;

	/**
	 * Set the callback, which returns the description as HTML.
	 *
	 * @param callable $callback The callback.
	 *
	 * @return void
	 */
	public function set_callback( callable $callback ): void {
		$this->callback = $callback;
	}

	/**
	 * Return the description, generated by the callback.
	 *
	 * @return string
	 */
	public function get_description(): string {
		if ( is_null( $this->callback ) ) {
			return parent::get_description();
		}
		if ( is_null( $this->generated ) ) {
			$description     = call_user_func( $this->callback );
			$this->generated = is_string( $description ) ? $description : '';
		}
		return $this->generated;
	}
}
